<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Balaji" failures="1" tests="1" name="com.sg.runner.RunnerFailedTest" time="10.100" errors="0" timestamp="2022-07-22T15:30:02 IST" skipped="0">
  <testcase classname="com.sg.runner.RunnerFailedTest" name="runScenario" time="10.100">
    <failure message="expected [https://opensource-demo.orangehrmlive.com/index.php/dashboard] but found [https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/index.php/dashboard] but found [https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.sg.steps.Demo1.i_should_get_access_to_the_portal_with_url_as(Demo1.java:48)
at âœ½.I should get access to the portal with url as 'https://opensource-demo.orangehrmlive.com/index.php/dashboard'(file:///D:/Mine/Company/Scientific%20Games3/automation_workspace/OrangeHRMBDD/src/test/resources/Feature/Login.feature:15)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- com.sg.runner.RunnerFailedTest -->
